java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/labs/rhodrif:latest'
  ingressHost: labs-rhodrif-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: labs
  environment:
